# Site settings
title: Ammonite
email: your-email@domain.com
description: "My blog about programming and video games."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://amm0nite.github.io" # the base hostname & protocol for your site
twitter_username: amm0nite
github_username:  amm0nite

# Build settings
markdown: kramdown
